/**
 * Media types for Payload CMS uploads
 */

import { PayloadDocument } from './payload';

/**
 * Image size variants generated by Payload
 */
export interface ImageSize {
  url: string;
  width: number;
  height: number;
  mimeType: string;
  filesize: number;
  filename: string;
}

/**
 * Available image size names
 */
export type ImageSizeName = 'thumbnail' | 'card' | 'hero';

/**
 * Media document from Payload CMS
 */
export interface Media extends PayloadDocument {
  filename: string;
  mimeType: string;
  filesize: number;
  width?: number;
  height?: number;
  alt?: string;
  url: string;
  sizes?: {
    thumbnail?: ImageSize;
    card?: ImageSize;
    hero?: ImageSize;
  };
}

/**
 * Media reference (can be string ID or full Media object)
 */
export type MediaReference = string | Media;
