#!/bin/bash

# Responsive Design Testing Script
# This script helps with manual responsive testing by providing instructions

echo "=========================================="
echo "Responsive Design Testing Script"
echo "Solar Cell CMS - Task 15"
echo "=========================================="
echo ""

# Check if dev server is running
if ! lsof -Pi :3000 -sTCP:LISTEN -t >/dev/null 2>&1 ; then
    echo "⚠️  Dev server is not running on port 3000"
    echo "Starting dev server..."
    npm run dev &
    DEV_SERVER_PID=$!
    echo "Dev server started with PID: $DEV_SERVER_PID"
    echo "Waiting for server to be ready..."
    sleep 5
else
    echo "✅ Dev server is already running on port 3000"
fi

echo ""
echo "=========================================="
echo "Testing Instructions"
echo "=========================================="
echo ""
echo "1. Open your browser to: http://localhost:3000"
echo "2. Open Chrome DevTools (F12 or Cmd+Option+I)"
echo "3. Click 'Toggle Device Toolbar' (Ctrl+Shift+M or Cmd+Shift+M)"
echo ""
echo "=========================================="
echo "Test Breakpoints"
echo "=========================================="
echo ""
echo "Desktop (1920px+):"
echo "  - Set viewport to: 1920 x 1080"
echo "  - Test all pages and components"
echo ""
echo "Tablet (768px-1919px):"
echo "  - Set viewport to: 768 x 1024 (iPad)"
echo "  - Set viewport to: 1024 x 768 (iPad Landscape)"
echo "  - Test all pages and components"
echo ""
echo "Mobile (320px-767px):"
echo "  - Set viewport to: 375 x 667 (iPhone SE)"
echo "  - Set viewport to: 414 x 896 (iPhone XR)"
echo "  - Set viewport to: 320 x 568 (iPhone 5/SE - smallest)"
echo "  - Test all pages and components"
echo ""
echo "=========================================="
echo "Pages to Test"
echo "=========================================="
echo ""
echo "1. Home Page: http://localhost:3000"
echo "   - Hero Section"
echo "   - Solar Calculator"
echo "   - Features Section"
echo "   - Lead Form"
echo "   - Call to Action"
echo ""
echo "2. Services Page: http://localhost:3000/services"
echo "   - Services Grid"
echo "   - Service Cards"
echo ""
echo "3. Service Detail: http://localhost:3000/services/[slug]"
echo "   - Service Header"
echo "   - Service Description"
echo "   - Image Gallery"
echo ""
echo "4. Reviews Page: http://localhost:3000/reviews"
echo "   - Reviews Grid"
echo "   - Review Cards"
echo ""
echo "5. Articles Page: http://localhost:3000/articles"
echo "   - Articles Grid"
echo "   - Article Cards"
echo ""
echo "6. Article Detail: http://localhost:3000/articles/[slug]"
echo "   - Article Header"
echo "   - Article Content"
echo "   - Featured Image"
echo ""
echo "=========================================="
echo "What to Check"
echo "=========================================="
echo ""
echo "✓ Layout adapts correctly to screen size"
echo "✓ Text is readable (not too small or too large)"
echo "✓ Images scale properly (no overflow or distortion)"
echo "✓ Navigation works (hamburger menu on mobile)"
echo "✓ Buttons are touch-friendly (min 44x44px)"
echo "✓ Forms are usable on all screen sizes"
echo "✓ Grid layouts adjust columns correctly"
echo "✓ Spacing is appropriate for each breakpoint"
echo "✓ No horizontal scrolling (except intentional)"
echo "✓ Content doesn't overlap or get cut off"
echo ""
echo "=========================================="
echo "Common Issues to Look For"
echo "=========================================="
echo ""
echo "❌ Text too small on mobile (< 16px)"
echo "❌ Touch targets too small (< 44x44px)"
echo "❌ Images overflow container"
echo "❌ Horizontal scrolling on mobile"
echo "❌ Content overlapping"
echo "❌ Navigation menu not working on mobile"
echo "❌ Forms difficult to use on mobile"
echo "❌ Grid not responsive (wrong number of columns)"
echo ""
echo "=========================================="
echo "Testing Tips"
echo "=========================================="
echo ""
echo "1. Test at exact breakpoint boundaries:"
echo "   - 767px (mobile max)"
echo "   - 768px (tablet min)"
echo "   - 1919px (tablet max)"
echo "   - 1920px (desktop min)"
echo ""
echo "2. Test smallest mobile size (320px)"
echo ""
echo "3. Test in both portrait and landscape"
echo ""
echo "4. Test touch interactions on mobile:"
echo "   - Tap buttons"
echo "   - Scroll"
echo "   - Fill forms"
echo "   - Open/close mobile menu"
echo ""
echo "5. Check performance on mobile:"
echo "   - Images load quickly"
echo "   - No layout shift"
echo "   - Smooth scrolling"
echo ""
echo "=========================================="
echo "Ready to test!"
echo "=========================================="
echo ""
echo "Press Ctrl+C to stop the dev server when done"
echo ""

# Keep script running
if [ ! -z "$DEV_SERVER_PID" ]; then
    wait $DEV_SERVER_PID
fi
